# Generated by Django 4.2.7 on 2023-11-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_items',
            fields=[
                ('mid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_items',
            fields=[
                ('fid', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('f_desc', models.TextField()),
                ('f_quantity', models.PositiveIntegerField(default=1)),
                ('f_price', models.PositiveIntegerField(default=30)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('f_img', models.ImageField(upload_to='')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menu_items')),
            ],
        ),
    ]
