# Generated by Django 4.2.7 on 2023-11-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
            ],
        ),
    ]
